# frozen_string_literal: true

require_relative 'podfile_helper'

platform :ios, '17.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release
}

flutter_sdk_root = PhotoboothPodfile.flutter_root(__dir__)
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_sdk_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods __dir__
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
