// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8wvvt_g153xx8J1DW0Di9E1vKf1zMfEc',
    appId: '1:957084044258:web:6b965ba5e2d192e54787bb',
    messagingSenderId: '957084044258',
    projectId: 'aiphotobooth-3b5e2',
    authDomain: 'aiphotobooth-3b5e2.firebaseapp.com',
    storageBucket: 'aiphotobooth-3b5e2.firebasestorage.app',
    measurementId: 'G-XP51B1BDJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkrkxsu-h-3X3dx-4Ct56baAKJP--F4zY',
    appId: '1:957084044258:android:4c1f8c8f5180a0a54787bb',
    messagingSenderId: '957084044258',
    projectId: 'aiphotobooth-3b5e2',
    storageBucket: 'aiphotobooth-3b5e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrpcK7LKYri3gfEURaOf3u0mUoouNVvXo',
    appId: '1:957084044258:ios:1c7bc1f482b161ca4787bb',
    messagingSenderId: '957084044258',
    projectId: 'aiphotobooth-3b5e2',
    storageBucket: 'aiphotobooth-3b5e2.firebasestorage.app',
    iosBundleId: 'com.prasthana.aceapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrpcK7LKYri3gfEURaOf3u0mUoouNVvXo',
    appId: '1:957084044258:ios:1c7bc1f482b161ca4787bb',
    messagingSenderId: '957084044258',
    projectId: 'aiphotobooth-3b5e2',
    storageBucket: 'aiphotobooth-3b5e2.firebasestorage.app',
    iosBundleId: 'com.prasthana.aceapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8wvvt_g153xx8J1DW0Di9E1vKf1zMfEc',
    appId: '1:957084044258:web:ded6f8b70104edd34787bb',
    messagingSenderId: '957084044258',
    projectId: 'aiphotobooth-3b5e2',
    authDomain: 'aiphotobooth-3b5e2.firebaseapp.com',
    storageBucket: 'aiphotobooth-3b5e2.firebasestorage.app',
    measurementId: 'G-8QP7WPL2L5',
  );

}