sonar.projectKey=palepujanakiram_photobooth
sonar.organization=palepujanakiram

# Paths are relative to this file (photobooth/).
sonar.sources=lib
sonar.sourceEncoding=UTF-8

# Disable C / C++ / Objective-C analysis
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
